twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        app_version: '%env(APP_VERSION)%'
        show_pwa_install_button: '%env(SHOW_PWA_INSTALL_BUTTON)%'