# Ścieżka do katalogu z serwerem
getServerPath: '/home/minecraft/server'
# Nazwa SCREENa
getScreenName: 'minecraft'
# Pobieranie ostatniego logu
getCurrentLog: 'cat %serverPath%/logs/latest.log'
# Szablon dla konsolowej komendy
getConsoleCommand: 'screen -S %screen% -p 0 -X stuff "%command%\r"'
# CPU usage
getCpuUsage: 'mpstat -P ALL 1 1 | grep Średnia'
# MEMORY usage
getMemoryUsage: "egrep 'Mem|Cache|Swap' /proc/meminfo"
# DISC usage
getDiscUsage: 'df -Th | grep /dev/sda1'
# Uptime
getUptime: 'uptime'
# Date
getDate: 'date'
# MC server status
getMcServerStatus: '/home/minecraft/bash/minecraft_backup.sh status'
# MC server restart
getMcServerRestart: '/home/minecraft/bash/minecraft_backup.sh restart'
# MC server stop
getMcServerStop: '/home/minecraft/bash/minecraft_backup.sh stop'
# MC server start
getMcServerStart: '/home/minecraft/bash/minecraft_backup.sh start'
# MC server backup
getMcServerBackup: '/home/minecraft/bash/minecraft_backup.sh backup'